# Generated by Django 3.2.8 on 2021-10-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RumahSakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tempat', models.CharField(choices=[('Sumatera', 'Sumatera'), ('Jakarta', 'DKI Jakarta'), ('Banten', 'Banten'), ('Bali', 'Bali'), ('NT', 'Nusa Tenggara'), ('Kalimantan', 'Kalimantan'), ('Sulawesi', 'Sulawesi'), ('Maluku', 'Maluku'), ('Papua', 'Papua')], max_length=12)),
                ('alamat', models.TextField(max_length=300)),
                ('antrian', models.IntegerField()),
                ('no_telfon', models.CharField(max_length=14)),
                ('kasurKosong', models.IntegerField()),
            ],
        ),
    ]
