# Generated by Django 3.2.8 on 2021-10-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSRujukan', '0002_bookingrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rumahsakit',
            name='antrian',
        ),
        migrations.RemoveField(
            model_name='rumahsakit',
            name='kasurKosong',
        ),
    ]
