# Generated by Django 3.2.8 on 2021-10-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSRujukan', '0003_auto_20211025_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumahsakit',
            name='tempat',
            field=models.CharField(choices=[('Sumatera', 'Sumatera'), ('Jakarta', 'DKI Jakarta'), ('Banten', 'Banten'), ('Bali', 'Bali'), ('Nusa Tenggara', 'Nusa Tenggara'), ('Kalimantan', 'Kalimantan'), ('Sulawesi', 'Sulawesi'), ('Maluku', 'Maluku'), ('Papua', 'Papua')], max_length=15),
        ),
    ]
