# Generated by Django 3.2.8 on 2021-10-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasiProtokol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='image_link',
            field=models.CharField(default='', max_length=400),
        ),
    ]
