# Generated by Django 3.2.8 on 2021-10-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasiProtokol', '0002_artikel_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='artikel_link',
            field=models.CharField(default='', max_length=400),
        ),
    ]
