# Generated by Django 3.2.8 on 2021-10-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasiProtokol', '0003_artikel_artikel_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='isi',
        ),
        migrations.AddField(
            model_name='artikel',
            name='deskripsi',
            field=models.CharField(default='', max_length=200),
        ),
    ]
