# Generated by Django 3.2.8 on 2021-10-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edukasiProtokol', '0004_auto_20211026_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='penulis',
            new_name='publisher',
        ),
    ]
