# Generated by Django 3.2.8 on 2021-10-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasiProtokol', '0005_rename_penulis_artikel_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='deskripsi',
            field=models.CharField(default='', max_length=85),
        ),
    ]
