# Generated by Django 3.2.8 on 2021-10-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasiProtokol', '0006_alter_artikel_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='tanggal_publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
