# Generated by Django 3.2.8 on 2021-10-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasiProtokol', '0010_alter_artikel_tanggal_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='tanggal_publish',
            field=models.CharField(max_length=10),
        ),
    ]
