# Generated by Django 3.2.8 on 2021-10-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasiProtokol', '0012_alter_artikel_tanggal_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='deskripsi',
            field=models.TextField(),
        ),
    ]
