# Generated by Django 3.2.8 on 2021-10-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasiProtokol', '0013_alter_artikel_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='judul',
            field=models.CharField(max_length=80),
        ),
    ]
