# Generated by Django 3.2.8 on 2021-10-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('asalUniversitas', models.CharField(max_length=30)),
                ('kotaBertugas', models.CharField(max_length=30)),
                ('pesan', models.TextField()),
            ],
        ),
    ]
