# Generated by Django 3.2.8 on 2021-10-25 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sebaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(max_length=64)),
                ('jumlah_kasus_terkonfirmasi', models.IntegerField()),
                ('jumlah_kasus_aktif', models.IntegerField()),
                ('jumlah_sembuh', models.IntegerField()),
                ('jumlah_meninggal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SebaranUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sebaran.sebaran')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
