# Generated by Django 3.2.8 on 2021-10-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sebaran', '0003_alter_sebaranuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sebaran',
            name='provinsi',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
