# Generated by Django 3.2.8 on 2021-10-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=200, verbose_name='Nama')),
                ('email', models.TextField(blank=True, max_length=50, verbose_name='Email')),
                ('nomor_kontak', models.TextField(blank=True, max_length=50, verbose_name='Nomor Kontak')),
            ],
        ),
    ]
