# Generated by Django 3.2.8 on 2021-10-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontak',
            name='email',
            field=models.CharField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='kontak',
            name='nama',
            field=models.CharField(max_length=200, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='kontak',
            name='nomor_kontak',
            field=models.CharField(max_length=200, verbose_name='Nomor Kontak'),
        ),
    ]
