# Generated by Django 3.2.8 on 2021-10-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layananisolasi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='Umur',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='Nama',
            new_name='untuk',
        ),
        migrations.RemoveField(
            model_name='note',
            name='Tempat',
        ),
        migrations.AddField(
            model_name='note',
            name='dari',
            field=models.TextField(default='', max_length=30),
        ),
    ]
